version: '3.6'

services:
  dalle-backend:
    container_name: dalle-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - app-cache:/root/.cache
      - library:/library
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

    networks:
      - dalle-internal-network

  dalle-interface:
    container_name: dalle-interface
    build:
      context: ./simple-interface
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - library:/app/library
      - library:/app/dalle-playground/library
    networks:
      - dalle-internal-network


  dalle-proxy-service:
    build: './proxyserver'
    container_name: dalle-proxy
    restart: always
    ports:
      - '8000:80'
    networks:
      - dalle-internal-network
      
networks:
  dalle-internal-network:
    name: dalle-internal-network

volumes:
  library:
    driver: local
  app-cache:
    driver: local