version: '3.6'

services:
  dalle-backend:
    container_name: dalle-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - app-cache-on-s:/root/.cache
      - library-on-s:/library
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    networks:
      - dalle-internal-network

  dalle-interface:
    container_name: dalle-interface
    build:
      context: ./simple-interface
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - library-on-s:/app/library
      - library-on-s:/app/dalle-playground/library
    networks:
      - dalle-internal-network

  dalle-scheduler:
    container_name: dalle-scheduler
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '6379:6379'
    volumes:
      - library-on-s:/app/library
    networks:
      - dalle-internal-network

  dalle-proxy-service:
    build: './proxyserver'
    container_name: dalle-proxy
    restart: always
    ports:
      - '8000:80'
    networks:
      - dalle-internal-network
      
networks:
  dalle-internal-network:
    name: dalle-internal-network

volumes:
  app-cache-on-s:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: S:\dalle\backend-cache
  library-on-s:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: S:\dalle\library